[package]
name = "noria-mysql"
version = "0.3.0"
authors = ["Malte Schwarzkopf <malte@csail.mit.edu>"]
edition = "2018"

[dependencies]
arccstr = "1.1.0"
clap = "2.24.0"
failure = "0.1.1"
msql-srv = "0.8.7"
noria = { git = "https://github.com/mit-pdos/noria.git" }
futures-executor-preview = "0.3.0-alpha.19"
futures-util-preview = "0.3.0-alpha.19"
lazy_static = "1.0.0"
nom-sql = "0.0.9"
slog = "2.4.0"
#slog = { version = "2.4.0", features = ["max_level_trace", "release_max_level_trace"] }
slog-term = "2.4.0"
regex = "1.0.0"
tokio = { version = "0.2.0-alpha.6", features = ["signal"] }
chrono = "0.4"
tracing = "0.1.3"
tracing-subscriber = { git = "https://github.com/tokio-rs/tracing.git" }
tracing-timing = { git = "https://github.com/jonhoo/tracing-timing.git", branch = "layer", features = ["layer"] }

[dev-dependencies]
mysql = "16"
zookeeper = "0.5.4"
noria-server = { git = "https://github.com/mit-pdos/noria.git" }

[profile.release]
debug=true

[lib]
path = "src/lib.rs"

###[patch."https://github.com/mit-pdos/noria.git"]
###noria = { path = "../noria/noria/" }
###noria-server = { path = "../noria/noria-server/" }

[patch.crates-io]
tokio-tower = { git = "https://github.com/tower-rs/tokio-tower.git", branch = "no-box" }
tokio-macros = { git = "https://github.com/tokio-rs/tokio.git" }
# https://github.com/hyperium/hyper/pull/2001
hyper = { git = "https://github.com/hyperium/hyper.git", rev = "e6027bc02db92d1137c54a26eef2e1cb4d810e25" }
# https://github.com/tokio-rs/tracing/pull/454
tracing-subscriber = { git = "https://github.com/tokio-rs/tracing.git" }
