[package]
name = "distributary-mysql"
version = "0.1.0"
authors = ["Malte Schwarzkopf <malte@csail.mit.edu>"]

[dependencies]
clap = "2.24.0"
msql-srv = "0.5"
#distributary = { path = "../distributary" }
distributary = { git = "https://github.com/mit-pdos/distributary.git", rev = "254ebf4533ffe3a2e55a08256238fd274fbb1f0d" }
lazy_static = "1.0.0"
nom_sql = { git = "https://github.com/ms705/nom-sql.git", rev = "9fd5a351ad542da7acccf11d290c5bc7c13f7fc9" }
slog = "2.0.6"
slog-term = "2.0.1"
regex = "0.2.6"

[dev-dependencies]
mysql = "12.0.4"
zookeeper = { git = "https://github.com/bonifaido/rust-zookeeper", rev = "1167cfce5f5088112bd53983614145e5787b4c8f" }

[lib]
name = "mysoupql"
path = "src/lib.rs"
