[package]
name = "distributary-mysql"
version = "0.1.0"
authors = ["Malte Schwarzkopf <malte@csail.mit.edu>"]

[dependencies]
arccstr = "1.0.4"
clap = "2.24.0"
msql-srv = "0.6"
#distributary = { path = "../distributary" }
distributary = { git = "https://github.com/mit-pdos/distributary.git", rev = "32680bd9772630be57a713d53046d75a2d86534e" }
lazy_static = "1.0.0"
nom-sql = { git = "https://github.com/ms705/nom-sql.git", rev = "c21878b78a13e79791972c7a74030fec04d89700" }
slog = "2.2.2"
#slog = { version = "2.2.2", features = ["max_level_trace", "release_max_level_trace"] }
slog-term = "2.3.0"
regex = "0.2.6"
chrono = "0.4"

[dev-dependencies]
mysql = "12.0.4"
zookeeper = { git = "https://github.com/bonifaido/rust-zookeeper", rev = "1167cfce5f5088112bd53983614145e5787b4c8f" }

[profile.release]
debug=true

[lib]
name = "mysoupql"
path = "src/lib.rs"
