[package]
name = "distributary-mysql"
version = "0.1.0"
authors = ["Malte Schwarzkopf <malte@csail.mit.edu>"]

[dependencies]
msql-srv = "0.5"
#distributary = { path = "../distributary" }
distributary = { git = "https://github.com/mit-pdos/distributary.git" }
nom_sql = { git = "https://github.com/ms705/nom-sql.git", rev = "75cec7e5c9104dd9ffbe979b6d881546a7ed2677" }
slog = "2.0.6"
slog-term = "2.0.1"
regex = "0.2.6"
#[bin]
#name = "mysoupql"
#path = "src/main.rs"
