[package]
name = "distributary-mysql"
version = "0.1.0"
authors = ["Malte Schwarzkopf <malte@csail.mit.edu>"]

[dependencies]
msql-srv = "0.2.1"
distributary = { git = "https://github.com/mit-pdos/distributary.git" }
slog = "2.0.6"
slog-term = "2.0.1"

#[bin]
#name = "mysoupql"
#path = "src/main.rs"
