[package]
name = "distributary-mysql"
version = "0.1.0"
authors = ["Malte Schwarzkopf <malte@csail.mit.edu>"]

[dependencies]
clap = "2.24.0"
msql-srv = "0.5"
#distributary = { path = "../distributary" }
distributary = { git = "https://github.com/mit-pdos/distributary.git" }
lazy_static = "1.0.0"
nom_sql = { git = "https://github.com/ms705/nom-sql.git", rev = "884e763ad7fe8bb49061c42131b377a387708e09" }
slog = "2.0.6"
slog-term = "2.0.1"
regex = "0.2.6"
#[bin]
#name = "mysoupql"
#path = "src/main.rs"
