[package]
name = "distributary-mysql"
version = "0.1.0"
authors = ["Malte Schwarzkopf <malte@csail.mit.edu>"]

[dependencies]
arccstr = "1.0.4"
clap = "2.24.0"
msql-srv = "0.6"
#distributary = { path = "../distributary" }
distributary = { git = "https://github.com/mit-pdos/distributary.git", rev = "d35ae8c663bcc5f0bc2adc5236910d16d7bbaf88" }
lazy_static = "1.0.0"
nom_sql = { git = "https://github.com/ms705/nom-sql.git", rev = "150437069ac936a95ad7d8049aafa3fc15b0ef3f" }
slog = "2.2.2"
slog-term = "2.3.0"
regex = "0.2.6"

[dev-dependencies]
mysql = "12.0.4"
zookeeper = { git = "https://github.com/bonifaido/rust-zookeeper", rev = "1167cfce5f5088112bd53983614145e5787b4c8f" }

[lib]
name = "mysoupql"
path = "src/lib.rs"
